openapi: 3.0.0
info:
  title: Insta viewer sample app
  description: Insta viewer sample app
  version: 1.0.0

tags:
  - name: user
    description: user endpoints

paths:
  /users/{login}:
    get:
      tags:
        - user
      description: get user info by id
      parameters:
        - in: path
          name: login
          description: login of user
          required: true
          schema:
            type: string
      responses:
        200:
          description: returns user info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'

components:
  parameters:
    AccessToken:
      in: path
      name: access_token
      required: true
      schema:
        type: string
  schemas:
    UserInfo:
      type: object
      description: Entity represeting instagram user info
      properties:
        id:
          type: string
          description: id of user
        login:
          type: string
          description: login of user
          example: piotrkav
        #add more here
